services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: . # <-- Context is ROOT
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/app
    env_file:
      - .env
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  worker:
    build:
      context: . # <-- Context is ROOT
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/code/app
    env_file:
      - .env
    command: python -m celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend